DROP DATABASE IF EXISTS imgpile;
CREATE DATABASE imgpile DEFAULT CHARACTER SET utf8;
USE imgpile;
CREATE TABLE image (
	id INT NOT NULL AUTO_INCREMENT,
	path VARCHAR(128) NOT NULL,
	name VARCHAR(64) NOT NULL,
	description VARCHAR(140),
	PRIMARY KEY (id)
) ENGINE InnoDB;
